"""durable Stars billing and subscription entitlements

Revision ID: 0bc58a691a8b
Revises: 4c137de92344
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0bc58a691a8b"
down_revision: str | None = "4c137de92344"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_operations",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("identity", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("token", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('processing','completed','uncertain')",
            name=op.f("ck_billing_operations_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_operations")),
        sa.UniqueConstraint("kind", "identity", name=op.f("uq_billing_operations_kind")),
    )
    op.create_table(
        "billing_products",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("subscription_period", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("plan IN ('pro', 'power')", name=op.f("ck_billing_products_paid_plan")),
        sa.CheckConstraint(
            "stars BETWEEN 1 AND 10000", name=op.f("ck_billing_products_stars_amount")
        ),
        sa.CheckConstraint(
            "subscription_period = 2592000", name=op.f("ck_billing_products_stars_period")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_billing_products")),
    )
    op.create_table(
        "billing_updates",
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("charge_id", sa.String(length=200), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','processed','rejected')", name=op.f("ck_billing_updates_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_updates")),
        sa.UniqueConstraint("event_type", "charge_id", name=op.f("uq_billing_updates_event_type")),
    )
    op.create_index(
        "ix_billing_updates_due", "billing_updates", ["status", "available_at"], unique=False
    )
    op.create_table(
        "checkout_intents",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("billing_product_code", sa.String(length=100), nullable=False),
        sa.Column("expected_amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_query_id", sa.String(length=200), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invoice_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "expected_amount > 0 AND currency = 'XTR'",
            name=op.f("ck_checkout_intents_stars_payment"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','paid','expired','cancelled')",
            name=op.f("ck_checkout_intents_status"),
        ),
        sa.ForeignKeyConstraint(
            ["billing_product_code"],
            ["billing_products.code"],
            name=op.f("fk_checkout_intents_billing_product_code_billing_products"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_checkout_intents_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkout_intents")),
    )
    op.create_index(
        "ix_checkout_pending_user",
        "checkout_intents",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "subscription_periods",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("payment_event_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "valid_until > valid_from", name=op.f("ck_subscription_periods_valid_period")
        ),
        sa.ForeignKeyConstraint(
            ["payment_event_id"],
            ["payment_events.id"],
            name=op.f("fk_subscription_periods_payment_event_id_payment_events"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_periods_subscription_id_subscriptions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_periods")),
        sa.UniqueConstraint(
            "payment_event_id", name=op.f("uq_subscription_periods_payment_event_id")
        ),
    )
    op.create_index(
        "ix_period_entitlement",
        "subscription_periods",
        ["subscription_id", "valid_until"],
        unique=False,
    )
    op.add_column(
        "payment_events",
        sa.Column("telegram_payment_charge_id", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "payment_events", sa.Column("billing_product_code", sa.String(length=100), nullable=True)
    )
    op.add_column("payment_events", sa.Column("subscription_id", sa.Uuid(), nullable=True))
    op.add_column("payment_events", sa.Column("plan", sa.String(length=20), nullable=True))
    op.create_index("ix_payment_subscription", "payment_events", ["subscription_id"], unique=False)
    op.create_unique_constraint(
        "uq_payment_charge_type",
        "payment_events",
        ["provider", "telegram_payment_charge_id", "event_type"],
    )
    op.drop_constraint(
        op.f("fk_payment_events_user_id_users"), "payment_events", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_payment_events_subscription_id_subscriptions"),
        "payment_events",
        "subscriptions",
        ["subscription_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_payment_events_billing_product_code_billing_products"),
        "payment_events",
        "billing_products",
        ["billing_product_code"],
        ["code"],
    )
    op.create_foreign_key(
        op.f("fk_payment_events_user_id_users"),
        "payment_events",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column("subscriptions", sa.Column("checkout_intent_id", sa.Uuid(), nullable=True))
    op.add_column(
        "subscriptions", sa.Column("billing_product_code", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "subscriptions",
        sa.Column("telegram_payment_charge_id", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "subscriptions", sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("UPDATE subscriptions SET valid_from = LEAST(created_at, valid_until)")
    op.alter_column("subscriptions", "valid_from", nullable=False)
    op.create_check_constraint(
        op.f("ck_subscriptions_paid_plan"), "subscriptions", "plan IN ('pro','power')"
    )
    op.create_check_constraint(
        op.f("ck_subscriptions_status"),
        "subscriptions",
        "status IN ('active','cancelled','expired','refunded')",
    )
    op.add_column(
        "subscriptions", sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "subscriptions", sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "ix_subscription_entitlement", "subscriptions", ["user_id", "valid_until"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_subscriptions_checkout_intent_id"), "subscriptions", ["checkout_intent_id"]
    )
    op.drop_constraint(op.f("fk_subscriptions_user_id_users"), "subscriptions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_subscriptions_billing_product_code_billing_products"),
        "subscriptions",
        "billing_products",
        ["billing_product_code"],
        ["code"],
    )
    op.create_foreign_key(
        op.f("fk_subscriptions_checkout_intent_id_checkout_intents"),
        "subscriptions",
        "checkout_intents",
        ["checkout_intent_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_subscriptions_user_id_users"),
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("users", "subscription_plan")
    op.execute("""
        CREATE FUNCTION ph_immutable_payment() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'Payment ledger is append-only'; END $$
    """)
    op.execute(
        "CREATE TRIGGER payment_immutable BEFORE UPDATE OR DELETE ON payment_events "
        "FOR EACH ROW EXECUTE FUNCTION ph_immutable_payment()"
    )
    op.execute("""
        CREATE FUNCTION ph_immutable_contract() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_TABLE_NAME = 'billing_products' THEN
            IF (NEW.code, NEW.plan, NEW.stars, NEW.subscription_period)
               IS DISTINCT FROM (OLD.code, OLD.plan, OLD.stars, OLD.subscription_period) THEN
              RAISE EXCEPTION 'Billing product price is immutable; create a new version';
            END IF;
          ELSE
            IF (NEW.user_id, NEW.billing_product_code, NEW.expected_amount, NEW.currency)
               IS DISTINCT FROM
                  (OLD.user_id, OLD.billing_product_code, OLD.expected_amount, OLD.currency) THEN
              RAISE EXCEPTION 'Checkout contract is immutable';
            END IF;
          END IF;
          RETURN NEW;
        END $$
    """)
    for table in ("billing_products", "checkout_intents"):
        op.execute(
            f"CREATE TRIGGER contract_immutable BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION ph_immutable_contract()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Deliberately refuse a destructive billing rollback after a real or simulated charge.
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM payment_events WHERE subscription_id IS NOT NULL) THEN
          RAISE EXCEPTION 'Archive billing data and use a forward migration; paid ledger exists';
        END IF;
    END $$""")
    op.execute("DROP TRIGGER payment_immutable ON payment_events")
    op.execute("DROP FUNCTION ph_immutable_payment()")
    for table in ("billing_products", "checkout_intents"):
        op.execute(f"DROP TRIGGER contract_immutable ON {table}")
    op.execute("DROP FUNCTION ph_immutable_contract()")
    op.drop_constraint(op.f("ck_subscriptions_paid_plan"), "subscriptions", type_="check")
    op.drop_constraint(op.f("ck_subscriptions_status"), "subscriptions", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "subscription_plan", sa.VARCHAR(length=20), server_default="free", nullable=False
        ),
    )
    op.alter_column("users", "subscription_plan", server_default=None)
    op.drop_constraint(op.f("fk_subscriptions_user_id_users"), "subscriptions", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_subscriptions_checkout_intent_id_checkout_intents"),
        "subscriptions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_subscriptions_billing_product_code_billing_products"),
        "subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_subscriptions_user_id_users"),
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("uq_subscriptions_checkout_intent_id"), "subscriptions", type_="unique")
    op.drop_index("ix_subscription_entitlement", table_name="subscriptions")
    op.drop_column("subscriptions", "refunded_at")
    op.drop_column("subscriptions", "cancelled_at")
    op.drop_column("subscriptions", "valid_from")
    op.drop_column("subscriptions", "telegram_payment_charge_id")
    op.drop_column("subscriptions", "billing_product_code")
    op.drop_column("subscriptions", "checkout_intent_id")
    op.drop_constraint(
        op.f("fk_payment_events_user_id_users"), "payment_events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_payment_events_billing_product_code_billing_products"),
        "payment_events",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_payment_events_subscription_id_subscriptions"),
        "payment_events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_payment_events_user_id_users"),
        "payment_events",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("uq_payment_charge_type", "payment_events", type_="unique")
    op.drop_index("ix_payment_subscription", table_name="payment_events")
    op.drop_column("payment_events", "plan")
    op.drop_column("payment_events", "subscription_id")
    op.drop_column("payment_events", "billing_product_code")
    op.drop_column("payment_events", "telegram_payment_charge_id")
    op.drop_index("ix_period_entitlement", table_name="subscription_periods")
    op.drop_table("subscription_periods")
    op.drop_index(
        "ix_checkout_pending_user",
        table_name="checkout_intents",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("checkout_intents")
    op.drop_index("ix_billing_updates_due", table_name="billing_updates")
    op.drop_table("billing_updates")
    op.drop_table("billing_products")
    op.drop_table("billing_operations")
    # ### end Alembic commands ###
