"""index notification cooldown lookups

Revision ID: 0f6ba52d97b6
Revises: caa0a3fed245
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0f6ba52d97b6"
down_revision: str | None = "caa0a3fed245"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_notifications_tracker_created",
        "notification_events",
        ["tracker_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_tracker_created", table_name="notification_events")
    # ### end Alembic commands ###
