"""canonical identifiers and product watches

Revision ID: 124441561d5e
Revises: 0bc58a691a8b
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "124441561d5e"
down_revision: str | None = "0bc58a691a8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_identifiers",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_identifiers_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_identifiers")),
        sa.UniqueConstraint(
            "product_id", "kind", "value", name=op.f("uq_product_identifiers_product_id")
        ),
    )
    op.create_index(
        "ix_product_identifier_lookup", "product_identifiers", ["kind", "value"], unique=False
    )
    op.create_table(
        "product_watches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("notify_on_new_best", sa.Boolean(), nullable=False),
        sa.Column("notify_on_price_drop", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("best_offer_id", sa.Uuid(), nullable=True),
        sa.Column("best_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("evaluation_sequence", sa.Integer(), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_product_watches_currency_code")
        ),
        sa.CheckConstraint(
            "target_price IS NULL OR target_price > 0",
            name=op.f("ck_product_watches_positive_target"),
        ),
        sa.ForeignKeyConstraint(
            ["best_offer_id"],
            ["store_offers.id"],
            name=op.f("fk_product_watches_best_offer_id_store_offers"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_watches_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_product_watches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_watches")),
        sa.UniqueConstraint(
            "user_id", "product_id", "currency", name=op.f("uq_product_watches_user_id")
        ),
    )
    op.create_index(
        op.f("ix_product_watches_product_id"), "product_watches", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_watches_user_id"), "product_watches", ["user_id"], unique=False
    )
    op.add_column("notification_events", sa.Column("product_watch_id", sa.Uuid(), nullable=True))
    op.add_column(
        "notification_events",
        sa.Column(
            "snapshot", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.alter_column("notification_events", "tracker_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        "ix_notifications_watch_created",
        "notification_events",
        ["product_watch_id", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_notification_events_product_watch_id_product_watches"),
        "notification_events",
        "product_watches",
        ["product_watch_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("products", sa.Column("mpn", sa.String(length=200), nullable=True))
    op.add_column(
        "store_offers",
        sa.Column(
            "identity_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "store_offers",
        sa.Column(
            "match_confidence", sa.Numeric(precision=4, scale=3), server_default="1", nullable=False
        ),
    )
    op.create_check_constraint(
        "one_subject",
        "notification_events",
        "(tracker_id IS NOT NULL)::int + (product_watch_id IS NOT NULL)::int = 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT EXISTS (SELECT 1 FROM product_watches)")):
        raise RuntimeError("Export/remove product watches explicitly before downgrading M3A")
    op.drop_constraint(
        op.f("ck_notification_events_one_subject"), "notification_events", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_offers", "match_confidence")
    op.drop_column("store_offers", "identity_data")
    op.drop_column("products", "mpn")
    op.drop_constraint(
        op.f("fk_notification_events_product_watch_id_product_watches"),
        "notification_events",
        type_="foreignkey",
    )
    op.drop_index("ix_notifications_watch_created", table_name="notification_events")
    op.alter_column("notification_events", "tracker_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("notification_events", "snapshot")
    op.drop_column("notification_events", "product_watch_id")
    op.drop_index(op.f("ix_product_watches_user_id"), table_name="product_watches")
    op.drop_index(op.f("ix_product_watches_product_id"), table_name="product_watches")
    op.drop_table("product_watches")
    op.drop_index("ix_product_identifier_lookup", table_name="product_identifiers")
    op.drop_table("product_identifiers")
    # ### end Alembic commands ###
