"""product discovery freshness and best price history

Revision ID: 2872920b653a
Revises: 124441561d5e
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2872920b653a"
down_revision: str | None = "124441561d5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "store_offers", sa.Column("refresh_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_discoveries",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("next_discovery_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=60), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_discoveries_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_discoveries")),
        sa.UniqueConstraint(
            "product_id",
            "provider",
            "country",
            "currency",
            name=op.f("uq_product_discoveries_product_id"),
        ),
    )
    op.create_index("ix_discovery_due", "product_discoveries", ["next_discovery_at"], unique=False)
    op.create_index(
        op.f("ix_product_discoveries_product_id"),
        "product_discoveries",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_best_states",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("store_offer_id", sa.Uuid(), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("next_evaluation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_best_states_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["store_offer_id"],
            ["store_offers.id"],
            name=op.f("fk_product_best_states_store_offer_id_store_offers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_best_states")),
        sa.UniqueConstraint(
            "product_id", "currency", name=op.f("uq_product_best_states_product_id")
        ),
    )
    op.create_index(
        "ix_best_state_expiry", "product_best_states", ["next_evaluation_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_best_states_product_id"),
        "product_best_states",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "best_price_events",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("store_offer_id", sa.Uuid(), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("store", sa.String(length=100), nullable=True),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_observation_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_best_price_events_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["source_observation_id"],
            ["price_observations.id"],
            name=op.f("fk_best_price_events_source_observation_id_price_observations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_offer_id"],
            ["store_offers.id"],
            name=op.f("fk_best_price_events_store_offer_id_store_offers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_best_price_events")),
        sa.UniqueConstraint(
            "product_id", "currency", "sequence", name=op.f("uq_best_price_events_product_id")
        ),
    )
    op.create_index(
        "ix_best_history",
        "best_price_events",
        ["product_id", "currency", "observed_at"],
        unique=False,
    )
    op.add_column(
        "product_watches", sa.Column("best_absence_reason", sa.String(length=30), nullable=True)
    )
    op.create_index(
        "ix_watches_product_currency", "product_watches", ["product_id", "currency"], unique=False
    )
    op.create_index(
        "ix_offers_product_currency", "store_offers", ["product_id", "currency"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT EXISTS (SELECT 1 FROM best_price_events)")):
        raise RuntimeError("Export best-price history explicitly before downgrading M3B")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_offers", "refresh_requested_at")
    op.drop_index("ix_offers_product_currency", table_name="store_offers")
    op.drop_index("ix_watches_product_currency", table_name="product_watches")
    op.drop_column("product_watches", "best_absence_reason")
    op.drop_index("ix_best_history", table_name="best_price_events")
    op.drop_table("best_price_events")
    op.drop_index(op.f("ix_product_best_states_product_id"), table_name="product_best_states")
    op.drop_index("ix_best_state_expiry", table_name="product_best_states")
    op.drop_table("product_best_states")
    op.drop_index(op.f("ix_product_discoveries_product_id"), table_name="product_discoveries")
    op.drop_index("ix_discovery_due", table_name="product_discoveries")
    op.drop_table("product_discoveries")
    # ### end Alembic commands ###
