"""index stalled notification delivery recovery

Revision ID: 4c137de92344
Revises: 0f6ba52d97b6
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4c137de92344"
down_revision: str | None = "0f6ba52d97b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_notifications_sending",
        "notification_events",
        ["attempt_started_at"],
        unique=False,
        postgresql_where=sa.text("status = 'sending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notifications_sending",
        table_name="notification_events",
        postgresql_where=sa.text("status = 'sending'"),
    )
    # ### end Alembic commands ###
