"""initial platform schema

Revision ID: caa0a3fed245
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "caa0a3fed245"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("identity_key", sa.String(length=64), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column("brand", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("gtin", sa.String(length=14), nullable=True),
        sa.Column("ean", sa.String(length=13), nullable=True),
        sa.Column("upc", sa.String(length=12), nullable=True),
        sa.Column("asin", sa.String(length=20), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("variant", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("identity_key", name=op.f("uq_products_identity_key")),
    )
    op.create_index(op.f("ix_products_gtin"), "products", ["gtin"], unique=False)
    op.create_table(
        "stores",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("domain", sa.String(length=200), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("supported", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("slug", name=op.f("uq_stores_slug")),
    )
    op.create_table(
        "users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("first_name", sa.String(length=200), nullable=True),
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("preferred_currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("subscription_plan", sa.String(length=20), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("referral_code", sa.String(length=32), nullable=True),
        sa.Column("referred_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["users.id"],
            name=op.f("fk_users_referred_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("referral_code", name=op.f("uq_users_referral_code")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "api_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("digest", name=op.f("uq_api_keys_digest")),
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "payment_events",
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_payment_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
        sa.UniqueConstraint(
            "provider", "external_event_id", name=op.f("uq_payment_events_provider")
        ),
    )
    op.create_table(
        "store_offers",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("direct_url", sa.String(length=2048), nullable=False),
        sa.Column("affiliate_url", sa.String(length=2048), nullable=True),
        sa.Column("affiliate_network", sa.String(length=80), nullable=True),
        sa.Column("affiliate_click_id", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("availability", sa.String(length=20), nullable=False),
        sa.Column("seller", sa.String(length=200), nullable=True),
        sa.Column("sku", sa.String(length=200), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("refresh_sequence", sa.Integer(), nullable=False),
        sa.Column("suspicious_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("suspicious_currency", sa.String(length=3), nullable=True),
        sa.Column("minimum_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("maximum_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=30, scale=4), nullable=False),
        sa.Column("observation_count", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_store_offers_positive_price")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_store_offers_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_offers_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_offers")),
        sa.UniqueConstraint("store_id", "external_id", name=op.f("uq_store_offers_store_id")),
    )
    op.create_index("ix_offers_due", "store_offers", ["next_check_at"], unique=False)
    op.create_index(
        op.f("ix_store_offers_product_id"), "store_offers", ["product_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "provider", "provider_subscription_id", name=op.f("uq_subscriptions_provider")
        ),
    )
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "price_observations",
        sa.Column("store_offer_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_key", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("availability", sa.String(length=20), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("price > 0", name=op.f("ck_price_observations_positive_price")),
        sa.ForeignKeyConstraint(
            ["store_offer_id"],
            ["store_offers.id"],
            name=op.f("fk_price_observations_store_offer_id_store_offers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_observations")),
        sa.UniqueConstraint("refresh_key", name=op.f("uq_price_observations_refresh_key")),
    )
    op.create_index(
        "ix_observation_offer_time",
        "price_observations",
        ["store_offer_id", "checked_at"],
        unique=False,
    )
    op.create_table(
        "trackers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("store_offer_id", sa.Uuid(), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("baseline_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("notify_on_any_drop", sa.Boolean(), nullable=False),
        sa.Column("notify_on_target", sa.Boolean(), nullable=False),
        sa.Column("notify_on_back_in_stock", sa.Boolean(), nullable=False),
        sa.Column("notify_on_historical_low", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("check_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_interval_seconds >= 30", name=op.f("ck_trackers_minimum_interval")
        ),
        sa.CheckConstraint(
            "target_price IS NULL OR target_price > 0", name=op.f("ck_trackers_positive_target")
        ),
        sa.ForeignKeyConstraint(
            ["store_offer_id"],
            ["store_offers.id"],
            name=op.f("fk_trackers_store_offer_id_store_offers"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trackers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trackers")),
        sa.UniqueConstraint("user_id", "store_offer_id", name=op.f("uq_trackers_user_id")),
    )
    op.create_index(
        op.f("ix_trackers_store_offer_id"), "trackers", ["store_offer_id"], unique=False
    )
    op.create_index(op.f("ix_trackers_user_id"), "trackers", ["user_id"], unique=False)
    op.create_table(
        "notification_events",
        sa.Column("tracker_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("deduplication_key", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tracker_id"],
            ["trackers.id"],
            name=op.f("fk_notification_events_tracker_id_trackers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_events")),
        sa.UniqueConstraint(
            "deduplication_key", name=op.f("uq_notification_events_deduplication_key")
        ),
    )
    op.create_index(
        "ix_notifications_pending",
        "notification_events",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notifications_pending",
        table_name="notification_events",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("notification_events")
    op.drop_index(op.f("ix_trackers_user_id"), table_name="trackers")
    op.drop_index(op.f("ix_trackers_store_offer_id"), table_name="trackers")
    op.drop_table("trackers")
    op.drop_index("ix_observation_offer_time", table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_store_offers_product_id"), table_name="store_offers")
    op.drop_index("ix_offers_due", table_name="store_offers")
    op.drop_table("store_offers")
    op.drop_table("payment_events")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("stores")
    op.drop_index(op.f("ix_products_gtin"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
