"""Destination preferences and source-bound delivery cache

Revision ID: d7a3b951e620
Revises: b65a7012c904
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d7a3b951e620"
down_revision: str | None = "b65a7012c904"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_quotes",
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_key", sa.String(length=64), nullable=False),
        sa.Column("item_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("offer_url", sa.String(length=2048), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("destination_key", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("shipping_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tax_status", sa.String(length=20), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("availability", sa.String(length=20), nullable=False),
        sa.Column("quoted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("delivered_total", sa.Numeric(precision=30, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "expires_at > quoted_at AND expires_at <= quoted_at + interval '1 day'",
            name=op.f("ck_delivery_quotes_quote_interval"),
        ),
        sa.CheckConstraint(
            "scope IN ('country','exact')", name=op.f("ck_delivery_quotes_destination_scope")
        ),
        sa.CheckConstraint(
            "status IN ('unsupported','incomplete','stale','failed','complete')",
            name=op.f("ck_delivery_quotes_quote_status"),
        ),
        sa.CheckConstraint(
            "tax_status != 'additional' OR tax_amount IS NOT NULL",
            name=op.f("ck_delivery_quotes_additional_tax_required"),
        ),
        sa.CheckConstraint(
            "tax_status IN ('included','additional','not_applicable','unknown')",
            name=op.f("ck_delivery_quotes_tax_status"),
        ),
        sa.CheckConstraint(
            "shipping_price IS NULL OR shipping_price >= 0",
            name=op.f("ck_delivery_quotes_nonnegative_shipping"),
        ),
        sa.CheckConstraint(
            "tax_amount IS NULL OR tax_amount >= 0", name=op.f("ck_delivery_quotes_nonnegative_tax")
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["store_offers.id"],
            name=op.f("fk_delivery_quotes_offer_id_store_offers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_quotes")),
        sa.UniqueConstraint(
            "offer_id",
            "destination_key",
            "scope",
            "currency",
            name=op.f("uq_delivery_quotes_offer_id"),
        ),
    )
    op.create_index("ix_delivery_quotes_expiry", "delivery_quotes", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_delivery_quotes_offer_id"), "delivery_quotes", ["offer_id"], unique=False
    )
    op.add_column(
        "store_offers",
        sa.Column("delivery_scope", sa.String(length=20), server_default="unknown", nullable=False),
    )
    op.add_column(
        "store_offers", sa.Column("delivery_destination_key", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "store_offers", sa.Column("delivery_currency", sa.String(length=3), nullable=True)
    )
    op.add_column(
        "store_offers", sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=True)
    )
    op.add_column(
        "store_offers",
        sa.Column("tax_status", sa.String(length=20), server_default="unknown", nullable=False),
    )
    op.add_column(
        "store_offers",
        sa.Column(
            "delivery_availability", sa.String(length=20), server_default="unknown", nullable=False
        ),
    )
    op.add_column(
        "store_offers", sa.Column("delivery_quoted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "store_offers", sa.Column("delivery_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "store_offers",
        sa.Column("delivery_item_price", sa.Numeric(precision=18, scale=4), nullable=True),
    )
    op.add_column(
        "store_offers",
        sa.Column("delivery_total", sa.Numeric(precision=30, scale=4), nullable=True),
    )
    # Legacy amount/country/tax placeholders remain unchanged but UNKNOWN: no
    # historical value proves currency, scope, availability, tax or quote age.
    # Remove duplicate private postal text, preserving only its opaque legacy key.
    op.execute("""UPDATE store_offers SET delivery_destination_key =
        encode(sha256(convert_to(jsonb_build_array(delivery_country, postal_code)::text,
        'UTF8')), 'hex') WHERE postal_code IS NOT NULL""")
    op.drop_column("store_offers", "postal_code")
    op.add_column("users", sa.Column("delivery_country", sa.String(length=2), nullable=True))
    op.add_column("users", sa.Column("delivery_postal_code", sa.String(length=20), nullable=True))
    op.create_check_constraint(
        op.f("ck_users_delivery_country_required"),
        "users",
        "delivery_postal_code IS NULL OR delivery_country IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(
        sa.text("""SELECT
        EXISTS (SELECT 1 FROM delivery_quotes) OR
        EXISTS (SELECT 1 FROM users WHERE delivery_country IS NOT NULL
            OR delivery_postal_code IS NOT NULL) OR
        EXISTS (SELECT 1 FROM store_offers WHERE delivery_scope != 'unknown'
            OR delivery_quoted_at IS NOT NULL OR delivery_destination_key IS NOT NULL
            OR delivery_currency IS NOT NULL OR tax_status != 'unknown'
            OR tax_amount IS NOT NULL OR delivery_total IS NOT NULL
            OR delivery_availability != 'unknown' OR delivery_expires_at IS NOT NULL)""")
    ):
        raise RuntimeError("Export delivery settings/evidence before downgrade")
    op.drop_constraint(op.f("ck_users_delivery_country_required"), "users", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "delivery_postal_code")
    op.drop_column("users", "delivery_country")
    op.add_column(
        "store_offers",
        sa.Column("postal_code", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.drop_column("store_offers", "delivery_expires_at")
    op.drop_column("store_offers", "delivery_item_price")
    op.drop_column("store_offers", "delivery_total")
    op.drop_column("store_offers", "delivery_quoted_at")
    op.drop_column("store_offers", "delivery_availability")
    op.drop_column("store_offers", "tax_status")
    op.drop_column("store_offers", "tax_amount")
    op.drop_column("store_offers", "delivery_currency")
    op.drop_column("store_offers", "delivery_destination_key")
    op.drop_column("store_offers", "delivery_scope")
    op.drop_index(op.f("ix_delivery_quotes_offer_id"), table_name="delivery_quotes")
    op.drop_index("ix_delivery_quotes_expiry", table_name="delivery_quotes")
    op.drop_table("delivery_quotes")
    # ### end Alembic commands ###
